[tools]
name='工具'
sort=1
    [[tools.sites]]
    url='https://haveibeenpwned.com'
    name='社工库'
    desc='密码泄漏查询'
    [[tools.sites]]
    url='http://www.stickpng.com'
    name='PNG搜索'
    desc='搜索PNG图片'
    [[tools.sites]]
    url='https://www.typingclub.com'
    name='TypingClub'
    desc='标准指法联系'
    [[tools.sites]]
    url='https://www.processon.com'
    name='ProcessOn'
    desc='在线流程图'
    [[tools.sites]]
    url='http://zhangweijie.cn/hq-icon/'
    name='icon查询'
    desc='查询应用ICON'
    [[tools.sites]]
    url='https://regexr.com/'
    name='在线正则'
    desc='在线正则测试'
    [[tools.sites]]
    url='https://colors.ichuantong.cn/'
    name='古典配色'
    desc='古典配色指南'
    [[tools.sites]]
    url='https://favicon.link/'
    name='Favicon'
    favicon='https://favicon.link/favicon.link'
    desc='favicon抓取'
    [[tools.sites]]
    url='https://h5-ocapp.onethingpcs.com/vPages/webapp/#/tasks/'
    name='玩客云'
    desc='玩客云网页'

[blog]
name='订阅'
sort=2
    [[blog.sites]]
    url='https://tech.meituan.com'
    name='美团技术团队'
    desc='美团技术分享'
    [[blog.sites]]
    url='http://vitrun.github.io'
    name='Food for Thought'
    desc='小志'
    [[blog.sites]]
    url='https://blog.alswl.com'
    name='Log4D'
    desc='3D'
    [[blog.sites]]
    url='https://javadoop.com'
    name='JavaDoop'
    desc='众安保险大佬Java分享'
    [[blog.sites]]
    url='https://gmem.site'
    name='绿色记忆'
    desc='全栈-汪震'
    [[blog.sites]]
    url='http://hengyunabc.github.io'
    name='横云断岭'
    desc='阿里-断岭'
    [[blog.sites]]
    url='http://hedengcheng.com'
    name='何登成的技术博客'
    desc='阿里DBA主管'
    [[blog.sites]]
    url='http://www.guxingke.com'
    name='孤星可'
    desc='堆糖小k'
    [[blog.sites]]
    url='https://www.flysnow.org'
    name='飞雪无情的博客'
    desc='Go实战笔记作者'
    [[blog.sites]]
    url='https://skyao.io/'
    name='敖小剑'
    desc='Service Mesh布道师'
    [[blog.sites]]
    url='https://hongjiang.info/'
    name='宏江大佬'
    desc='挖财-宏江'
    [[blog.sites]]
    url='http://tech.dianwoda.com/'
    name='点我达'
    desc='点我达技术博客'
    [[blog.sites]]
    url='https://tech.songxiaocai.com/posts/index.html/'
    name='宋小菜'
    desc='宋小菜技术博客'
    [[blog.sites]]
    url='https://www.yumingyuan.me/'
    name='鱼头的博客'
    desc='极客-鱼头'
    [[blog.sites]]
    url='https://draveness.me/'
    name='面向信仰编程'
    desc='draveness'
    [[blog.sites]]
    url='http://www.mybatis.cn/'
    name='mybatis中文网'
    desc='mybatis'
    [[blog.sites]]
    url='https://www.throwable.club'
    name='throwable'
    desc='java'

[forum]
name='资讯'
sort=3
    [[forum.sites]]
    url='https://www.tonymacx86.com/'
    name='tonymacx86'
    desc='黑苹果论坛'
    [[forum.sites]]
    url='https://www.v2ex.com/'
    name='V2EX'
    desc='V2EX论坛'
    [[forum.sites]]
    url='https://www.52pojie.cn/forum-21-1.html'
    name='52破解'
    desc='52破解资源站'
    [[forum.sites]]
    url='https://www.iplaysoft.com/'
    name='异次元软件'
    desc='软件资讯'
    [[forum.sites]]
    url='https://sspai.com/'
    name='少数派'
    favicon='https://cdn.sspai.com/sspai/assets/img/favicon/icon.ico'
    desc='苹果派'
    [[forum.sites]]
    url='http://free.apprcn.com/'
    name='反斗限免'
    desc='APP限免资讯'
    [[forum.sites]]
    url='https://www.waerfa.com/'
    name='Mac玩儿法'
    desc='Mac软件资讯'
    [[forum.sites]]
    url='http://www.chuapp.com'
    name='触乐'
    desc='触乐游戏资讯'
    [[forum.sites]]
    url='https://www.ifanr.com'
    name='爱泛儿'
    desc='爱泛儿资讯'
    [[forum.sites]]
    url='https://www.chiphell.com/'
    name='Chiphell'
    desc='Chiphell论坛'
    [[forum.sites]]
    url='http://www.dgtle.com/'
    name='数字尾巴'
    desc='数码资讯社区'
    [[forum.sites]]
    url='https://creatorsdaily.com/'
    name='创造者日报'
    desc='每日一个产品'
    [[forum.sites]]
    url='https://eleduck.com/'
    name='电鸭社区'
    desc='远程工作社区'
    [[forum.sites]]
    url='https://indiehackers.net/'
    name='独立开发者'
    desc='独立开发者社区'
    [[forum.sites]]
    url='https://www.expreview.com/top'
    name='超能网'
    desc='评测媒体'

[developer]
name='开发'
sort=4
    [[developer.sites]]
        url='https://blog.jetbrains.com/platform/'
        name='Jetbrains Blog'
        desc='Jetbrains咨询'
    [[developer.sites]]
        url='https://intellij-support.jetbrains.com'
        name='Jetbrains Plugin'
        desc='Plugin Develop'
    [[developer.sites]]
        url='https://www.8btc.com/book'
        name='巴比特'
        desc='巴比特图书'
    [[developer.sites]]
        url='https://db-engines.com/en/ranking'
        name='DB排名'
        desc='DB排名'
    [[developer.sites]]
        url='https://mirrors.cloud.tencent.com/'
        name='腾讯云开源镜像'

[design]
name='设计'
sort=5
    [[design.sites]]
    url='https://www.pinterest.com/'
    name='pinterest'
    desc='pinterest'
    [[design.sites]]
    url='https://www.maliquankai.com/'
    name='maliquankai'
    desc='码力全开设计站'

[resource]
name='资源'
sort=6
    [[resource.sites]]
    url='https://weread.qq.com/'
    name='微信读书'
    desc='微信读书'
    [[resource.sites]]
    url='https://www.yunpanjingling.com'
    name='云盘精灵'
    desc='百度云资源'
    [[resource.sites]]
    url='http://ddrk.me/'
    name='低端影视'
    desc='高清电影在线'
    [[resource.sites]]
    url='https://www.sq688.com/'
    name='无损音乐'
    desc='无损音乐下载'
    [[resource.sites]]
    url='https://unsplash.com/'
    name='unsplash'
    desc='壁纸'
    [[resource.sites]]
    url='http://www.btbtt.me/'
    name='BT之家'
    desc='BT之家'
    [[resource.sites]]
    url='http://www.rrys.tv/'
    name='人人影视'
    desc='人人影视'
    [[resource.sites]]
    url='https://rsshub.ioiox.com'
    name='RSSHub'
    desc='大佬的RSSHub'
    [[resource.sites]]
    url='https://yabook.org'
    name='电子书'
    desc='电子书网站'
    [[resource.sites]]
    url='http://www.lingocn.com/'
    name='电子书2'
    desc='电子书网站2'
    [[resource.sites]]
    url='http://www.mvcat.com/'
    name='电影全网搜'
    desc='电影全网搜'

[other]
name='其他'
sort=666
 [[other.sites]]
    url='https://bwh1.net/cart.php?a=add&pid=27'
    name='搬瓦工'
    desc='VPS'
 [[other.sites]]
    url='https://jinkela.pw'
    name='金坷垃'
    desc='VPS'
 [[other.sites]]
    url='https://github.com/layonhands/jinkela'
    name='金坷垃备份'
    desc='VPS'
 [[other.sites]]
    url='https://www.vultr.com/'
    name='Vultr'
    desc='Vultr'
