[blog]
name='博客'
sort=1
    [[blog.sites]]
    url='https://mrdear.cn/atom.xml'
    name='屈定的blog'
    [[blog.sites]]
    url='https://blog.alswl.com/atom.xml'
    name='3D的博客'
    [[blog.sites]]
    url='https://draveness.me/feed.xml'
    name='面向信仰编程'
    [[blog.sites]]
    url='https://rsshub.ioiox.com/meituan/tech/home'
    favicon='https://cdn-1251403103.file.myqcloud.com/tech.meituan.com/32'
    name='美团技术博客'
    [[blog.sites]]
    url='https://rsshub.ioiox.com/blogs/wangyin'
    favicon='https://www.yinwang.org/images/Yc.jpg'
    name='王垠博客'
    [[blog.sites]]
    url='http://www.mybatis.cn/feed'
    name='mybatis中文网'
    [[blog.sites]]
    url='https://www.throwable.club/atom.xml'
    name='throwable个人博客'
    [[blog.sites]]
    url='https://www.elastic.co/cn/blog/feed'
    name='ES博客'
[itNews]
name='IT资讯'
sort=2
    [[itNews.sites]]
    url='https://sspai.com/feed'
    favicon='https://cdn.sspai.com/sspai/assets/img/favicon/icon.ico'
    name='少数派'
    [[itNews.sites]]
    url='https://www.expreview.com/rss.php'
    name='超能网'
    [[itNews.sites]]
    url='https://www.ifanr.com/feed'
    name='爱范儿'
    [[itNews.sites]]
    url='https://feed.iplaysoft.com'
    favicon='https://cdn-1251403103.file.myqcloud.com/www.iplaysoft.com/32'
    name='异次元软件'
    [[itNews.sites]]
    url='https://www.oschina.net/news/rss?show=project'
    name='软件更新'
    [[itNews.sites]]
    url='https://rsshub.ioiox.com/smzdm/haowen/fenlei/diannaoshuma'
    name='ZDM-数码'
[resources]
name='资源'
sort=3
    [[resources.sites]]
    url='https://creatorsdaily.com/api/rss'
    name='创造者日报'
