[blog]
name='博客'
sort=1
    [[blog.sites]]
    url='https://mrdear.cn/atom.xml'
    name='屈定的blog'
[itNews]
name='IT咨询'
sort=2
    [[itNews.sites]]
    url='https://sspai.com/feed'
    favicon='https://cdn.sspai.com/sspai/assets/img/favicon/icon.ico'
    name='少数派'
    [[itNews.sites]]
    url='http://free.apprcn.com/category/ios/feed/'
    name='反斗IOS限免'
    [[itNews.sites]]
    url='http://free.apprcn.com/category/mac/feed/'
    name='反斗MAC限免'